version: 2

jobs:
   build_frontend:
     working_directory: ~/OSUApp/
     docker:
       - image: circleci/node:6.11.4
     steps:
       - checkout
       - run: #TODO remove
          name: List Frontend Folder
          command: 'cd frontend/osuApp && ls'
       - run:
          name: Node version
          command: 'node -v'
       - run:
          name: Update npm
          command: 'cd frontend/osuApp && sudo npm install -g npm@latest'
       -run:
          name: Install Angular CLI
          command: 'cd frontend/osuApp && sudo npm install -g @angular/cli@latest'
       - run:
          name: Install npm
          command: 'cd frontend/osuApp && npm install'
   test_frontend:
       working_directory: ~/OSUApp
       docker:
         - image: circleci/node:6.11.4
       steps:
         - checkout
         - run:
            name: Test
            command: 'cd frontend/osuApp && ng test'

   build_backend:
      docker:
        # specify the version you desire here
        - image: circleci/openjdk:8-jdk

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/postgres:9.4

      working_directory: ~/OSUApp/backend

      steps:
        - checkout

        - run:
           name: List Backend Folder
           command: 'cd backend && ls'

        - run:
           name: Run Gradle dependencies
           command: 'cd backend && gradle dependencies'

   test_backend:
     docker:
        # specify the version you desire here
        - image: circleci/openjdk:8-jdk
     steps:
        - checkout

        - run:
           name: Run Test
           command: 'cd backend && gradle test'

workflows:
  version: 2
  build:
    jobs:
      - build_frontend
      - build_backend
      - test_frontend:
          requires:
            - build_frontend
      - test_backend:
          requires:
            - build_backend
