version: 2

jobs:
   build_frontend:
     working_directory: ~/osu-app/
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run:
          name: Go to Frontend Folder
          command: 'cd frontend'
       - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: Install npm
          command: npm install
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
   test_frontend:
       working_directory: ~/osu-app/OSUApp/frontend/osuApp
       docker:
         - image: circleci/node:6
       steps:
         - checkout
         - run:
            name: Test
            command: ng test

workflows:
  version: 2
  build_and_test_frontend:
    jobs:
      - build_frontend
      - test_frontend:
          requires:
            - build_frontend
          filters:
            branches:
              only: master
